name: Deploy to Firebase
on:
  push:
    branches: master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # ou la version que vous utilisez
      
      - name: Install dependencies
        run: npm ci  # ou yarn install si vous utilisez Yarn
      
      - name: Build project
        run: npm run build  # ou la commande appropriée pour votre projet
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}